# Generated by Django 5.2.1 on 2025-05-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_delete_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delete',
        ),
        migrations.DeleteModel(
            name='Update',
        ),
    ]
